name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    secrets: inherit
  deploy:
    name: Deploy contracts
    uses: ./.github/workflows/deploy.yml
    needs: test
    secrets: inherit
    with:
      environment: testnet
