name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run tests
    uses: ./.github/workflows/test.yml
    with:
      privateKey: ${{ secrets.PRIVATE_KEY }}
      marketServiceFee: ${{ secrets.MARKET_SERVICE_FEE }}
