name: CI

on:
  push:
    branches:
      - develop
      - feature/CC-87
  pull_request:
    branches:
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
