name: Deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
      MARKET_SERVICE_FEE: ${{ secrets.MARKET_SERVICE_FEE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Compile
        run: yarn compile
      - name: Deploy to Rinkeby network
        if: ${{ inputs.environment == 'testnet' }}
        run: yarn deploy --network ethRinkeby
      - name: Deploy to Rinkeby network
        if: ${{ inputs.environment == 'mainnet' }}
        run: yarn deploy --network ethMainnet