name: Test

on:
  workflow_call:
    inputs:
      privateKey:
        required: true
        type: string
      marketServiceFee:
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY: ${{ inputs.privateKey }}
      MARKET_SERVICE_FEE: ${{ inputs.marketServiceFee }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Generate typings
        run: yarn typegen
      - name: Run tests
        run: yarn test
